#### `Column space`, or `range` of a matrix

For a matrix $A\in \mathbf{R}^{m \times n}$, its `column space` is defined as

$$R(A)=\{Ax |x\in\mathbf{R}^n\}$$

$R(A)$ is always a `subspace` of $\mathbf{R}^m$

* $R(A)$ is a set all possible $y$ as the output of $Ax$
* $R(A)$ is a set of $y$ for which $y=Ax$ has a solution (not necessarily unique solution)
* $R(A)=\text{span}(a_1, a_2,\cdots, a_n)$, where $a_i$'s are columns of $A$

#### In case of $R(A)$=$\mathbf{R}^m$

$A$ is called `onto` if $R(A)=\mathbf{R}^m$ $\Longleftrightarrow$

* $y=Ax$ can be solved in $x$ for any $y$ (not necessarily unique solution)
* columns of $A$ span $\mathbf{R}^m$
* $A$ has `right inverse`, $B\in \mathbf{R}^{n \times m}$, such that $AB=I$. So, $A(By)=y$ and $y=Ax$, we have $x=By+\{z|z\in N(A)\}$. This means $x$ is a `linear combination` of columns in $B$ where $y$ are the `coefficients`
* `rows` of $A$ are `independent`
* $N(A^T)=\{0\}$
* $\det(AA^T)\neq 0$

#### Show the `last three`

We see if we can show

* `rows` of $A$ are `independent`
* $N(A^T)=\{0\}$

Then through transpose of $A$ and properties of `zero nullspace`, we would get
* $\det(AA^T)\neq 0$

##### $N(A^T)=\{0\}$

Since $R(A)=\mathbf{R}^m$, then, there does `not` exist a vector $z\in \mathbf{R}^m$ that is `orthogonal to all columns` in $A$ (Otherwise, $\dim R(A) < m$)

As a result, for $A^T\in \mathbf{R}^{n \times m}$, `no` non-zero $z\in \mathbf{R}^m$ can satisfy

$$A^Tz=0$$

as it would require $z$ being orthogonal to all rows in $A^T$ (`2nd` interpretation of matrix-vector multiplication: as inner product with rows in matrix)

Therefore, $N(A^T)=\{0\}$

##### Rows of `A` are independent

As $N(A^T)=\{0\}$, from properties of `zero nullspace`, columns of $A^T$ are `independent`

So, rows of $A$ are independent

#### `Left` and `right` inverse

If $A$ has a `right inverse` $B$, then

$$(AB)^T=B^TA^T=I$$

That is, $B^T$ is a `left inverse` of $A^T$

Since $N(A^T)=\{0\}$ and $N(A^T)=\{0\}$ $\Longleftrightarrow$ $A^T$ has left inverse, then

* $A$ must have `right inverse`
* $A$ can only be `fat` or `square` matrix
* its right inverse is in the form of transposed left inverse of $A^T$
* first, we replace $A$ with $A^T$ in `left inverse` of $A$ (from last notebook)

$$(A^TA)^{-1}A^T$$

to get `left inverse` of $A^T$

$$(AA^T)^{-1}A$$

Then, we transpose it to get `right inverse` of $A$

$$((AA^T)^{-1}A)^T=A^T((AA^T)^{-1})^T=A^T((AA^T)^T)^{-1}=\boxed{A^T(AA^T)^{-1}}$$

#### The `right` right inverse

We have a matrix

$$A=\begin{bmatrix}
-1 & 0 & 0 & -1 & 1 \\ 0 & 1 & 1 & 0 & 0 \\ 1 & 0 & 0 &1 & 0
\end{bmatrix}$$

For this matrix $R(A)=\mathbf{R}^3$, so it has right inverse, but can we find the `right` right inverse that has the following properties?

In [1]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

In [2]:
A=np.array([[-1, 0, 0, -1, 1], [0, 1, 1, 0, 0], [1, 0, 0, 1, 0]])

(1) second row of $B$ is zero

This means second column in $A$ is not used in forming $AB$. We can write $\bar{A}$ as the matrix $A$ with its second column removed. Since $\bar{A}$ is still full rank, we can compute right inverse using $\bar{B}=\bar{A}^T(\bar{A}\bar{A}^T)^{-1}$. Finally, we insert a row of zeros to the second row

In [3]:
A_bar = np.delete(A, 1, axis=1)
print(f"A_bar: \n{A_bar}")
B_bar = A_bar.T @ np.linalg.inv(A_bar @ A_bar.T)
print(f"\nB_bar: \n{B_bar}")
zero_row = np.zeros(B_bar.shape[1])
B = np.insert(B_bar, 1, zero_row, axis=0)
print(f"\nB: \n{B}")

# Verify orthogonality
print(f"\nA @ B: \n{A @ B}")

A_bar: 
[[-1  0 -1  1]
 [ 0  1  0  0]
 [ 1  0  1  0]]

B_bar: 
[[ 0.0000  0.0000  0.5000]
 [ 0.0000  1.0000  0.0000]
 [ 0.0000  0.0000  0.5000]
 [ 1.0000  0.0000  1.0000]]

B: 
[[ 0.0000  0.0000  0.5000]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  1.0000  0.0000]
 [ 0.0000  0.0000  0.5000]
 [ 1.0000  0.0000  1.0000]]

A @ B: 
[[ 1.0000  0.0000 -0.0000]
 [ 0.0000  1.0000  0.0000]
 [ 0.0000  0.0000  1.0000]]


(2) the nullspace of $B$ has dimension one

This means $B$ has rank 2, therefore, the rank of $AB$ is at most 2, making it impossible that $AB$ is full rank as $I$ is

(3) the second and third rows of $B$ are the same

Let $\bar{B}$ be $B$ with one of the rows 2 and 3 deleted. We have $AB=\bar{A}\bar{B}$, where $\bar{A}$ is obtained from $A$ by replacing its second column with sum of second and third columns, and deleting its third column. Since $\bar{A}$ is still full rank, we can get $\bar{B}$ as before. And we insert a copy of second row as new third row.

In [4]:
A_bar = A.copy()
A_bar[:, 1] = A[:, 1] + A[:, 2]
A_bar = np.delete(A_bar, 2, axis=1)
print(f"A_bar: \n{A_bar}")

B_bar = A_bar.T @ np.linalg.inv(A_bar @ A_bar.T)
print(f"\nB_bar: \n{B_bar}")

row_2 = B_bar[1,:]
B = np.insert(B_bar, 2, row_2, axis=0)
print(f"\nB: \n{B}")

# Verify orthogonality
print(f"\nA @ B: \n{A @ B}")

A_bar: 
[[-1  0 -1  1]
 [ 0  2  0  0]
 [ 1  0  1  0]]

B_bar: 
[[ 0.0000  0.0000  0.5000]
 [ 0.0000  0.5000  0.0000]
 [ 0.0000  0.0000  0.5000]
 [ 1.0000  0.0000  1.0000]]

B: 
[[ 0.0000  0.0000  0.5000]
 [ 0.0000  0.5000  0.0000]
 [ 0.0000  0.5000  0.0000]
 [ 0.0000  0.0000  0.5000]
 [ 1.0000  0.0000  1.0000]]

A @ B: 
[[ 1.0000  0.0000 -0.0000]
 [ 0.0000  1.0000  0.0000]
 [ 0.0000  0.0000  1.0000]]
