#### `QR` decomposition

In basic G-S, given $a_1, \cdots, a_k \in \mathbf{R}^n$ are `independent`, we found the expression of $a_i$ as `linear combination` of `orthonormal` $q_1,\cdots, q_i$

$$a_i = (q_1^Ta_i)q_1 + (q_2^Ta_i)q_2 +\cdots+ (q_{i-1}^Ta_i)q_{i-1} + \|\tilde{q_i}\|q_i$$

Let $q_j^Ta_i=r_{ji}$ and $\|\tilde{q_i}\|=r_{ii}$, we have

$$a_i = r_{1i}q_1 + r_{2i}q_2 +\cdots+ r_{(i-1)i}q_i+ r_{ii}q_i$$

If we write this in matrix form, let $A\in \mathbf{R}^{n \times k}$, $Q\in \mathbf{R}^{n \times k}$, and $R\in \mathbf{R}^{k \times k}$, we have

$$\begin{bmatrix}a_1 & a_2 & \cdots & a_k\end{bmatrix}=\begin{bmatrix}q_1 & q_2 & \cdots & q_k\end{bmatrix}\begin{bmatrix}r_{11} & r_{12} & \cdots & r_{1k} \\ 0 & r_{22} & \cdots & r_{2k} \\ \vdots & \vdots & \ddots & \vdots \\ 0 & 0& \cdots & r_{kk} \end{bmatrix}$$

This is `QR decomposition` of $A$, where columns of $Q$ are `orthonormal basis` for $R(A)$ (not necessarily $\mathbf{R}^n$)

#### `General` Gram-Schmidt

If, however, $a_1, \cdots, a_k$ are `not independent`, then some $a_i$ can be expressed as linear combination of $a_1, \cdots, a_{i-1}$

As a result, $\tilde{q_i}=0$

In `general` G-S, when we encouter $\tilde{q_i}=0$, we simply `skip` this $a_i$ and move to $a_{i+1}$

#### Example

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

plt.style.use('dark_background')
# color: https://matplotlib.org/stable/gallery/color/named_colors.htm

In [ ]:
def general_gram_schmidt(A):
    _, k = A.shape  # Get number of vectors (columns) in A
    Q = []  # Start with empty list, as we don't know how many q's are there
    R = np.zeros((0, k))  # Same here

    for i in range(k):
        # Loop over all a_i
        q = A[:, i].copy()

        # Remove components of a in the direction of previous q's
        # This skips when i=0
        for j in range(len(Q)):
            R[j, i] = np.dot(Q[j], A[:, i])
            q -= R[j, i] * Q[j] # -(q_j^T a_i)q_j

        # Compute norm of new q
        norm_q = np.sqrt(np.dot(q, q))

        # Only add q to Q if it is not small
        if norm_q > 1e-10:  # Tolerance
            q /= norm_q
            Q.append(q)

            # Expand R to include new row corresponding to new q
            new_row = np.zeros((1, k))
            new_row[0, i] = norm_q
            R = np.vstack([R, new_row])

    Q = np.column_stack(Q)  # Convert to array

    return Q, R

In [ ]:
A = np.array([[1.0, 2.0, 1.0 + 2.0, -1.0, 2.0],
              [4.0, 1.0, 4.0 + 1.0, -4.0, 3.0],
              [3.0, 5.0, 3.0 + 5.0, -3.0, 7.0],
              [2.0, 0.0, 2.0 + 0.0, -2.0, 3.0]])

Q, R = general_gram_schmidt(A)

print("Orthonormal basis Q:")
print(Q)

print("\nUpper staircase matrix R:")
print("Stairs indicate where q's are found")
print(R)

# Verify Q is orthonormal
print(f"\nQ^TQ:\n{np.dot(Q.T, Q)}")
print(f"Norms: \n{np.linalg.norm(Q, axis=0)}")

# Verify that A = QR
A_reconstructed = np.dot(Q, R)
print("\nOriginal matrix A:")
print(A)
print("\nReconstructed matrix A from Q and R:")
print(A_reconstructed)

Orthonormal basis Q:
[[ 0.1826  0.3324 -0.2692]
 [ 0.7303 -0.4602 -0.4888]
 [ 0.5477  0.7414  0.2054]
 [ 0.3651 -0.3579  0.8040]]

Upper staircase matrix R:
Stairs indicate where q's are found
[[ 5.4772  3.8341  9.3113 -5.4772  7.4855]
 [ 0.0000  3.9115  3.9115 -0.0000  3.4002]
 [ 0.0000  0.0000  0.0000  0.0000  1.8453]]

Q^TQ:
[[ 1.0000  0.0000 -0.0000]
 [ 0.0000  1.0000 -0.0000]
 [-0.0000 -0.0000  1.0000]]
Norms: 
[ 1.0000  1.0000  1.0000]

Original matrix A:
[[ 1.0000  2.0000  3.0000 -1.0000  2.0000]
 [ 4.0000  1.0000  5.0000 -4.0000  3.0000]
 [ 3.0000  5.0000  8.0000 -3.0000  7.0000]
 [ 2.0000  0.0000  2.0000 -2.0000  3.0000]]

Reconstructed matrix A from Q and R:
[[ 1.0000  2.0000  3.0000 -1.0000  2.0000]
 [ 4.0000  1.0000  5.0000 -4.0000  3.0000]
 [ 3.0000  5.0000  8.0000 -3.0000  7.0000]
 [ 2.0000 -0.0000  2.0000 -2.0000  3.0000]]
