#### `Gain` of a matrix

Let $A\in \mathbf{R}^{m \times n}$ (tall, square or fat), for $x\in \mathbf{R}^n$

$$\frac{\|Ax\|}{\|x\|}$$

gives the `amplification factor` or `gain` of $A$ `in the direction` of $x$

#### `Largest` gain and `matrix norm`

The largest gain

$$\max\frac{\|Ax\|}{\|x\|}, x\neq0$$

is known as `matrix norm` or `spectral norm` of $A$, written as $\|A\|$

Recall the upper and lower bound of quadratic form in terms of the eigenvalues of a matrix

$$\lambda_{s,min} \|x\|^2 \leq x^TSx \leq \lambda_{s,max} \|x\|^2 $$

we have

$$\max\frac{\|Ax\|^2}{\|x\|^2}=\max\frac{x^T(A^TA)x}{\|x\|^2}=\boxed{\lambda_{max} \,(A^TA)}$$

Therefore, the matrix norm is

$$\|A\|=\sqrt{\lambda_{max} \,(A^TA)}$$

$A^TA\in \mathbf{R}^{n \times n}$ is symmetric and $\boxed{A^TA\geq0}$

#### `Smallest` gain

Similarly

$$\min\frac{\|Ax\|}{\|x\|}, x\neq0=\sqrt{\lambda_{min} \,(A^TA)}$$

So

* `max gain` input direction is $x=q_1$, eigenvector of $A^TA$ associated with $\lambda_{max}$
* `min gain` input direction is $x=q_n$, eigenvector of $A^TA$ associated with $\lambda_{min}$

`Nullspace`, for example, represents the `directions` where gain is `zero`

In case $Ax$ is tiny, which for practical purposes can be considered as $x\in N(A)$, matrix norm gives a quantitative way of talking about `nullspace`

In [1]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

In [2]:
tall_matrix=False

if tall_matrix:
    A = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])
else:
    A = np.array([[1, 3, 5],
                  [2, 4, 6]])

A_TA = np.dot(A.T, A)

eigenvalues, eigenvectors = np.linalg.eig(A_TA)

print(f'Eigenvalues \n{eigenvalues}')
print(f'\nEigenvectors \n{eigenvectors}')
print(f'\nA_TA \n{A_TA}')
print(f'\nReconstructed matrix \n{eigenvectors @ np.diag(eigenvalues) @ eigenvectors.T}')

Eigenvalues 
[ 90.7355  0.2645  0.0000]

Eigenvectors 
[[-0.2298 -0.8835  0.4082]
 [-0.5247 -0.2408 -0.8165]
 [-0.8196  0.4019  0.4082]]

A_TA 
[[ 5 11 17]
 [11 25 39]
 [17 39 61]]

Reconstructed matrix 
[[ 5.0000  11.0000  17.0000]
 [ 11.0000  25.0000  39.0000]
 [ 17.0000  39.0000  61.0000]]


In case of `fat matrix` here, smallest gain is zero as $A^TA$ is low rank and is guaranteed to have non-trivial `nullspace`