#### Similar to `full` $QR$, we can extend SVD to `full SVD`

For $A\in \mathbf{R}^{m \times n}$ with $\text{rank}(A)=r$, its `compact` SVD is given by

$$A=U\Sigma V^T=\begin{bmatrix}u_1 & \cdots & u_r\end{bmatrix}\begin{bmatrix}\sigma_1 &  & \\  & \ddots & \\  &  & \sigma_r \end{bmatrix}\begin{bmatrix}v_1^T \\ \vdots \\ v_r^T\end{bmatrix}=\sum_{i=1}^r\sigma_i u_i v_i^T$$

where
* $U\in \mathbf{R}^{m \times r}$, $U^TU=I$
* $V\in \mathbf{R}^{n \times r}$, $V^TV=I$
* $\Sigma =\text{diag}(\sigma_1, \cdots, \sigma_r)$
* $\sigma_1, \cdots, \sigma_r$ are `nonzero` singular values of $A$
* $v_i\in \mathbf{R}^n$ are `right singular vectors` of $A$
* $u_i\in \mathbf{R}^m$ are `left singular vectors` of $A$

We can then find $U_2\in \mathbf{R}^{m \times (m-r)}$ and $V_2\in \mathbf{R}^{n \times (n-r)}$ such that $U=\begin{bmatrix}U_1 & U_2\end{bmatrix}\in \mathbf{R}^{m \times m}$ and $V=\begin{bmatrix}V_1 & V_2\end{bmatrix}\in \mathbf{R}^{n \times n}$ are `orthogonal matrices`

Now, we can express `full SVD`, with $\Sigma \in \mathbf{R}^{m \times n}$ as



$$A=U\Sigma V^T=\begin{bmatrix}U_1 & U_2\end{bmatrix}\begin{bmatrix}\begin{bmatrix}\sigma_1 &  & \\  & \ddots & \\  &  & \sigma_r \end{bmatrix} & 0_{r \times (n-r)} \\ 0_{(m-r) \times r} & 0_{(m-r) \times (n-r)}  \end{bmatrix}\begin{bmatrix}V_1^T \\  V_2^T\end{bmatrix}$$

In [8]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

In [9]:
A_tall = np.array([[1, 2 ,1],
                  [3, 4, 3],
                  [5, 6, 5] ,
                  [2.5, 3, 2.5],
                  [2.5, 3, 2.5]])

# When full_matrices=False, size of sigma is smallest dim of A's height and width, not rank of A
U, sigma, Vt = np.linalg.svd(A_tall, full_matrices=False)

# So we manually truncate zero singular values and corresponding u and v
non_zero_indices = sigma > 1e-10
U = U[:, non_zero_indices]
sigma = sigma[non_zero_indices]
Vt = Vt[non_zero_indices, :]

print(f'A shape m x n: \n{A_tall.shape[0]} x {A_tall.shape[1]}')
print(f'rank A r: \n{np.linalg.matrix_rank(A_tall)}')
print(f'\nU from compact SVD (m x r): \n{U}')
print(f'\nSigma from compact SVD (r x r): \n{np.diag(sigma)}')
print(f'\nV from compact SVD (n x r): \n{Vt.T}')
print(f'\nReconstruct A from compact SVD: \n{U @ np.diag(sigma) @ Vt}')

A shape m x n: 
5 x 3
rank A r: 
2

U from compact SVD (m x r): 
[[-0.1836 -0.8887]
 [-0.4488 -0.3044]
 [-0.7141  0.2799]
 [-0.3570  0.1399]
 [-0.3570  0.1399]]

Sigma from compact SVD (r x r): 
[[ 12.9845  0.0000]
 [ 0.0000  0.6351]]

V from compact SVD (n x r): 
[[-0.5303  0.4677]
 [-0.6615 -0.7500]
 [-0.5303  0.4677]]

Reconstruct A from compact SVD: 
[[ 1.0000  2.0000  1.0000]
 [ 3.0000  4.0000  3.0000]
 [ 5.0000  6.0000  5.0000]
 [ 2.5000  3.0000  2.5000]
 [ 2.5000  3.0000  2.5000]]


In [10]:
U_full, sigma_full, Vt_full = np.linalg.svd(A_tall, full_matrices=True)

# Full sigma would have same size as A_tall
Sigma_full = np.zeros_like(A_tall)
# Fill in singular values
np.fill_diagonal(Sigma_full, sigma_full)

print(f'A shape m x n: \n{A_tall.shape[0]} x {A_tall.shape[1]}')
print(f'\nU from full SVD (m x m): \n{U_full}')
print(f'\nRank U: \n{np.linalg.matrix_rank(U_full)}')
print(f'\nSigma from full SVD (m x n, same shape as A): \n{Sigma_full}')
print(f'\nV from full SVD (n x n): \n{Vt_full.T}')
print(f'\nRank V: \n{np.linalg.matrix_rank(Vt_full)}')
print(f'\nReconstruct A from full SVD: \n{U_full @ Sigma_full @ Vt_full}')

A shape m x n: 
5 x 3

U from full SVD (m x m): 
[[-0.1836 -0.8887 -0.4201  0.0000 -0.0000]
 [-0.4488 -0.3044  0.8402  0.0000  0.0000]
 [-0.7141  0.2799 -0.2801 -0.4082 -0.4082]
 [-0.3570  0.1399 -0.1400  0.9082 -0.0918]
 [-0.3570  0.1399 -0.1400 -0.0918  0.9082]]

Rank U: 
5

Sigma from full SVD (m x n, same shape as A): 
[[ 12.9845  0.0000  0.0000]
 [ 0.0000  0.6351  0.0000]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000]]

V from full SVD (n x n): 
[[-0.5303  0.4677  0.7071]
 [-0.6615 -0.7500  0.0000]
 [-0.5303  0.4677 -0.7071]]

Rank V: 
3

Reconstruct A from full SVD: 
[[ 1.0000  2.0000  1.0000]
 [ 3.0000  4.0000  3.0000]
 [ 5.0000  6.0000  5.0000]
 [ 2.5000  3.0000  2.5000]
 [ 2.5000  3.0000  2.5000]]
