#### `Left` and `right` inverses can be computed via SVD

If a matrix $A$ is `tall and full rank`, its `left inverse` (that gives `least squares` solution) is given by

$$V\Sigma^{-1}U^T=(A^TA)^{-1}A^T$$

In [ ]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

In [ ]:
A_tall = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

U, sigma, Vt = np.linalg.svd(A_tall, full_matrices=False)

# Left inverse from inverse of SVD
left_inv_svd = Vt.T @ np.diag(1 / sigma) @ U.T

# Left inverse from (A^TA)^{-1}A^T
left_inv_formula = np.linalg.inv(A_tall.T @ A_tall) @ A_tall.T

print('Left inverse from SVD\n', left_inv_svd)
print('\nLeft inverse from formula\n', left_inv_formula)

Left inverse from SVD
 [[-1.3333 -0.3333  0.6667]
 [ 1.0833  0.3333 -0.4167]]

Left inverse from formula
 [[-1.3333 -0.3333  0.6667]
 [ 1.0833  0.3333 -0.4167]]


If a matrix $A$ is `fat and full rank`, its `right inverse` (that gives `least norm` solution) is also given by

$$V\Sigma^{-1}U^T=A^T(AA^T)^{-1}$$

In [ ]:
A_fat = np.array([[1, 3, 5],
                  [2, 4, 6]])

# Note NumPy gives V.T, not V
U, sigma, Vt = np.linalg.svd(A_fat, full_matrices=False)

# Left inverse from inverse of SVD
right_inv_svd = Vt.T @ np.diag(1 / sigma) @ U.T

# Left inverse from A^T(AA^T)^{-1}
right_inv_formula = A_fat.T @ np.linalg.inv(A_fat @ A_fat.T)

print('Right inverse from SVD\n', right_inv_svd)
print('\nRight inverse from formula\n', right_inv_formula)

Right inverse from SVD
 [[-1.3333  1.0833]
 [-0.3333  0.3333]
 [ 0.6667 -0.4167]]

Right inverse from formula
 [[-1.3333  1.0833]
 [-0.3333  0.3333]
 [ 0.6667 -0.4167]]


These two particular inverses often refered to as `pseudo inverse` or `Moore-Penrose inverse`

Proof: https://arxiv.org/pdf/1110.6882