#### Left and right inverses can be computed via SVD

If a matrix $A\in R^{m\times n}$ is `tall and full rank`, its `left inverse` (that gives `least squares` solution) is given by

$$V\Sigma^{+}U^T=(A^TA)^{-1}A^T$$

denote $\Sigma_n^{-1}=\text{diag}\left(\frac{1}{\sigma_1},\cdots, \frac{1}{\sigma_n}\right)$ with $\Sigma^{+}\in R^{n\times m}=[\Sigma_n^{-1}\,\,0]$ denoting rectangular version padded with zeros and 

$$A=U\Sigma V^T$$

where $U=[U_{1, m\times n} \,\,U_{2, m\times (m-n)}]$

For the corresponding least squares (and write $x=Vz$)

$$||y-Ax||_2^2=||y-U\Sigma V^TVz||_2^2=||y-U\Sigma z||_2^2$$

Use orthogonality of $U$ (which does not change norm), we have

$$||y-U\Sigma z||_2=||U^T y-\Sigma z||_2$$

Let

$$c = U^T y =\begin{bmatrix}U_1^T \\U_2^T\end{bmatrix} y=\begin{bmatrix}c_1 \\c_2\end{bmatrix}, \Sigma =\begin{bmatrix}\Sigma_n \\ 0\end{bmatrix}$$

then 

$$\begin{align*}||c-\Sigma z||_2^2 &= \begin{Vmatrix}\begin{bmatrix}c_1\\c_2\end{bmatrix}-\begin{bmatrix}\Sigma_n z\\0\end{bmatrix}\end{Vmatrix}_2^2 \\
&=||c_1-\Sigma_n z||_2^2+||c_2||_2^2
\end{align*}$$

The second term does not depend on $z$, so the minimizer is

$$z^*=\Sigma_n^{-1}c_1$$

Plug everything back

$$x^*=Vz^*=V\Sigma_n^{-1}c_1 = V\Sigma_n^{-1}U_1^T y=V[\Sigma_n^{-1} \,\,0]\begin{bmatrix}U_1^T \\U_2^T\end{bmatrix}y$$

which is exactly $$x^*=V\Sigma^{+}U^Ty$$

In [ ]:
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

In [ ]:
A_tall = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

U, sigma, Vt = np.linalg.svd(A_tall, full_matrices=False)

# Left inverse from inverse of SVD
left_inv_svd = Vt.T @ np.diag(1 / sigma) @ U.T

# Left inverse from (A^TA)^{-1}A^T
left_inv_formula = np.linalg.inv(A_tall.T @ A_tall) @ A_tall.T

print('Left inverse from SVD\n', left_inv_svd)
print('\nLeft inverse from formula\n', left_inv_formula)

Left inverse from SVD
 [[-1.3333 -0.3333  0.6667]
 [ 1.0833  0.3333 -0.4167]]

Left inverse from formula
 [[-1.3333 -0.3333  0.6667]
 [ 1.0833  0.3333 -0.4167]]


If a matrix $A$ is `fat and full rank`, its `right inverse` (that gives `least norm` solution) is also given by

$$V\Sigma^{+}U^T=A^T(AA^T)^{-1}$$

Let $x=Vz\in R^n$, $\Sigma = [\Sigma_m \,\,0]$, $c=U^Ty\in R^m$, $\Sigma^{+} = \begin{bmatrix}\Sigma_m^{-1} \\ 0\end{bmatrix}$

then

$$||y-Ax||_2^2 = ||c-[\Sigma_m \,\,0]z||_2^2 = ||c-[\Sigma_m \,\,0]\begin{bmatrix}z_1 \\z_2\end{bmatrix}||_2^2$$

with $z_1\in R^m, z_2\in R^{n-m}$

Apparently, the solution is $z_1^*=\Sigma_m^{-1}c$ while $z_2$ is arbitrary, and 

$$x=V\begin{bmatrix}\Sigma_m^{-1}c \\z_2\end{bmatrix}$$

The least-norm solution is achieved by choosing $z_2=0$

$$z^*=\begin{bmatrix}\Sigma_m^{-1}c \\0\end{bmatrix} \Longrightarrow x^*=V\begin{bmatrix}\Sigma_m^{-1}c \\0\end{bmatrix}=V\Sigma^+U^Ty$$

In [ ]:
A_fat = np.array([[1, 3, 5],
                  [2, 4, 6]])

# Note NumPy gives V.T, not V
U, sigma, Vt = np.linalg.svd(A_fat, full_matrices=False)

# Left inverse from inverse of SVD
right_inv_svd = Vt.T @ np.diag(1 / sigma) @ U.T

# Left inverse from A^T(AA^T)^{-1}
right_inv_formula = A_fat.T @ np.linalg.inv(A_fat @ A_fat.T)

print('Right inverse from SVD\n', right_inv_svd)
print('\nRight inverse from formula\n', right_inv_formula)

Right inverse from SVD
 [[-1.3333  1.0833]
 [-0.3333  0.3333]
 [ 0.6667 -0.4167]]

Right inverse from formula
 [[-1.3333  1.0833]
 [-0.3333  0.3333]
 [ 0.6667 -0.4167]]


These two particular inverses often refered to as `pseudo inverse` or `Moore-Penrose inverse`