#### LU factorization

Gaussian elimination is the simplest way to solve linear systems of equations, which transforms a full linear system into an upper-triangular one by applying simple linear transformations over `rows`

Unlike Householder, transformations applied in Gaussian elimination are `not orthogonal`

This procedure can be illustrated using a matrix $A\in \mathbf{R}^{4 \times 4}$ where `x` indicates entries that are not necessarily zero

At each iteration, multiples of the current row is `subtracted` from subsequent rows, such that zeros are introduced below the diagonal sequentially

$$A:\begin{bmatrix} \times & \times & \times & \times\\\times & \times & \times& \times\\\times & \times & \times& \times\\\times & \times & \times& \times\end{bmatrix} \rightarrow L_1A\rightarrow \begin{bmatrix} \times & \times & \times & \times\\ 0& \times & \times& \times\\ 0 & \times & \times& \times\\ 0 & \times & \times& \times\end{bmatrix}\rightarrow L_2L_1A\rightarrow\begin{bmatrix} \times & \times & \times & \times\\ 0& \times & \times& \times\\ 0 & 0 & \times& \times\\ 0 & 0 & \times& \times\end{bmatrix}\rightarrow L_3L_2L_1A\rightarrow U: \begin{bmatrix} \times & \times & \times & \times\\ 0& \times & \times& \times\\ 0 & 0 & \times& \times\\ 0 & 0 & 0& \times\end{bmatrix}$$

where $L_i\in \mathbf{R}^{4 \times 4}, i=1, 2, 3$

For example, if

$$A=\begin{bmatrix}2 & 1 & 1 & 0 \\ 4 & 3 & 3 & 1 \\ 8 & 7 & 9 & 5 \\ 6 & 7 & 9 & 8\end{bmatrix}$$

then, as first iteration

$$L_1A = \begin{bmatrix}1 & 0 & 0 & 0 \\ -2 & 1 & 0 & 0 \\ -4 & 0 & 1 & 0 \\ -3 & 0 & 0 & 1\end{bmatrix}\begin{bmatrix}2 & 1 & 1 & 0 \\ 4 & 3 & 3 & 1 \\ 8 & 7 & 9 & 5 \\ 6 & 7 & 9 & 8\end{bmatrix} = \begin{bmatrix}2 & 1 & 1 & 0 \\ 0 & 1 & 1 & 1 \\ 0 & 3 & 5 & 5 \\ 0 & 4 & 6 & 8\end{bmatrix}$$

That is, we multiply first row by 2, and subtract it from second row, multiply first row by 4 and subtract it from third row, and multiply first row by 3, and subtract it from fourth row

#### Pivoting

At each `kth` iteration, we see that basically we are free to choose any entry in the submatrix $A_{k:m,k:m}$ and turn other entries in $A_{k:m,k}$ into zero, as long as we don't forget to `permute` the columns and rows before elimination to keep the output in correct shape

For example, in `2nd` iteration as follows, we can first swap the 2nd and 4th row and then do the elimination

$$ L_1A: \begin{bmatrix} \times & \times & \times & \times\\ 0& \times & \times& \times\\ 0 & \times & \times& \times\\ 0 & \color{orange}{\times} & \color{red}{\times}& \color{red}{\times}\end{bmatrix}\rightarrow P_2L_1A \begin{bmatrix} \times & \times & \times & \times\\ 0& \color{orange}{\times} & \color{red}{\times}& \color{red}{\times}\\ 0 & \times & \times& \times\\ 0 & \times & \times& \times\end{bmatrix} \rightarrow L_2P_2L_1A\rightarrow\begin{bmatrix} \times & \times & \times & \times\\ 0 & \color{orange}{\times} & \color{red}{\times}& \color{red}{\times}\\ 0 & 0 & \times& \times\\ 0 & 0 & \times& \times\end{bmatrix}$$

and the permutation matrix $P_2$ is

$$P_2=\begin{bmatrix} 1 & 0 &0 & 0\\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \\ 0 & 1 & 0 & 0\end{bmatrix}$$

For numerical reasons, it is prefered to choose the largest entry in absolute value in submatrix $A_{k:m,k:m}$ to serve as the leading element in the diagnoal for the row in concern. However, looking through all entries in $A_{k:m,k:m}$ can be time consuming if the matrix is large. Therefore, often we only swap the `rows` by left multiplying $P$, rather than columns, by examining the elements in $A_{k:m,k}$

The leading element in the selected row is called `pivot` (the orange $\times$ in the illustration)

If no row swap is needed, then $P$ is the identity matrix

#### Put everything together

We now can write out the Gaussian elimination procedure through LU factorization

$$L_3P_3L_2P_2L_1P_1A=U$$

and we can rewrite it as

$$L_3'L_2'L_1'P_3P_2P_1=L_3(P_3L_2P_3^{-1})(P_3P_2L_1P_2^{-1}P_3^{-1})P_3P_2P_1A=L_3P_3L_2P_2L_1P_1A=U$$

In general, for $A\in\mathbf{R}^{m\times m}$, we have

$$(L_{m-1}'\cdots L_2'L_1')(P_{m-1}\cdots P_2P_1)A=U$$

where

$$L_k'=P_{m-1}\cdots P_{k+1}L_kP_{k+1}^{-1}\cdots P_{m-1}^{-1}$$

and $L_k'$ is $L_k$ but with `subdiagonal entries permuted`

This follows from that, first, when a square permutation matrix involves only swapping two rows, its inverse is the matrix itself

Therefore, $P_i=P_i^{-1}$, and by sandwiching $L_k$ between $P_{k+1}$ and $P_{k+1}^{-1}$, what $P_{k+1}L_kP_{k+1}^{-1}$ does to $L_k$ is simply swapping two columns and the corresponding two rows

However, since $P_{k+1}$ can only work on `(k+1)th` and lower rows of $L_k$, and $P_{k+1}^{-1}$ can only work on `(k+1)th` and righter columns of $L_k$, and by construction, $L_k$ still follows an identity matrix other than the first `k` columns, therefore, by swapping rows and columns for `(k+1)th` row and `(k+1)th` column onwards, the only effect would be permuting the subdiagonal entries for the first `k` columns of $L_k$

For illustration, consider the `2nd` iteration when $L_1$ is

$$L_1=\begin{bmatrix} 1 & 0 & 0 & 0 \\
-2 & 1 & 0 & 0 \\ -4 & 0 & 1 & 0 \\ -3 & 0 & 0 & 1\end{bmatrix}$$

If we need to swap row 2, 4 using $P_2$, then

$$P_2L_1P_2^{-1}=\begin{bmatrix} 1 & 0 &0 & 0\\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \\ 0 & 1 & 0 & 0\end{bmatrix}\begin{bmatrix} 1 & 0 & 0 & 0 \\
-2 & 1 & 0 & 0 \\ -4 & 0 & 1 & 0 \\ -3 & 0 & 0 & 1\end{bmatrix}\begin{bmatrix} 1 & 0 &0 & 0\\ 0 & 0 & 0 & 1 \\ 0 & 0 & 1 & 0 \\ 0 & 1 & 0 & 0\end{bmatrix}=\begin{bmatrix} 1 & 0 & 0 & 0 \\
-3 & 1 & 0 & 0 \\ -4 & 0 & 1 & 0 \\ -2 & 0 & 0 & 1\end{bmatrix}$$

and we can verify similarly for $P_3P_2L_1P_2^{-1}P_3^{-1}$

#### Example

In [1]:
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

plt.style.use('dark_background')
# color: https://matplotlib.org/stable/gallery/color/named_colors.htm

In [2]:
def lu_factorization(A):
    m, n = A.shape
    u_mat = A.copy().astype(float)
    l_mat = np.identity(m)
    p_mat = np.identity(m)

    for k in range(m-1):
        # Find pivot
        pivot = np.argmax(np.abs(u_mat[k:, k])) + k

        if pivot != k:
            # Swap rows in u, p, and l
            u_mat[[k, pivot], :] = u_mat[[pivot, k], :]
            p_mat[[k, pivot], :] = p_mat[[pivot, k], :]
            l_mat[[k, pivot], :k] = l_mat[[pivot, k], :k]

        for j in range(k + 1, m):
            l_mat[j, k] = u_mat[j, k] / u_mat[k, k]
            # Subtract multiply of kth row from jth row
            u_mat[j, k:] -= l_mat[j, k] * u_mat[k, k:]

    return p_mat, l_mat, u_mat

In [3]:
A = np.array([[2, 1, 1, 0], [4, 3, 3, 1], [8, 7, 9, 5], [6, 7, 9, 8]])

p_mat, l_mat, u_mat = lu_factorization(A)

print('P:\n', p_mat)
print('L:\n', l_mat)
print('U:\n', u_mat)

print('PA:\n', p_mat @ A)
print('LU:\n', l_mat @ u_mat)

P:
 [[ 0.0000  0.0000  1.0000  0.0000]
 [ 0.0000  0.0000  0.0000  1.0000]
 [ 0.0000  1.0000  0.0000  0.0000]
 [ 1.0000  0.0000  0.0000  0.0000]]
L:
 [[ 1.0000  0.0000  0.0000  0.0000]
 [ 0.7500  1.0000  0.0000  0.0000]
 [ 0.5000 -0.2857  1.0000  0.0000]
 [ 0.2500 -0.4286  0.3333  1.0000]]
U:
 [[ 8.0000  7.0000  9.0000  5.0000]
 [ 0.0000  1.7500  2.2500  4.2500]
 [ 0.0000  0.0000 -0.8571 -0.2857]
 [ 0.0000  0.0000  0.0000  0.6667]]
PA:
 [[ 8.0000  7.0000  9.0000  5.0000]
 [ 6.0000  7.0000  9.0000  8.0000]
 [ 4.0000  3.0000  3.0000  1.0000]
 [ 2.0000  1.0000  1.0000  0.0000]]
LU:
 [[ 8.0000  7.0000  9.0000  5.0000]
 [ 6.0000  7.0000  9.0000  8.0000]
 [ 4.0000  3.0000  3.0000  1.0000]
 [ 2.0000  1.0000  1.0000  0.0000]]
