#### Factorization of `positive definite` matrices

Every positive definite matrix $A$ has a Cholesky factorization that is unique

$$A=LL^T$$

where $L$ is lower triangular

To get a feeling of how to find the factorization, we look at the first step (since $A$ is positive definite, $a_{11}>0$)

$$\begin{align*}A &= \begin{bmatrix} a_{11} & w^T \\ w &
K \end{bmatrix} \\
&=\begin{bmatrix} \sqrt{a_{11}} & 0\\ w/\sqrt{a_{11}} &
I \end{bmatrix}\begin{bmatrix} 1 & 0 \\ 0 &
K-ww^T/a_{11}\end{bmatrix}\begin{bmatrix} \sqrt{a_{11}} & w^T/\sqrt{a_{11}} \\ 0 &
I \end{bmatrix} \\
&=L_1A_1L_1^T
\end{align*}$$

We can keep going and decompose $A_1=L_2A_2L_2^T$ and so on and we have

$$A=L_1\cdots L_mL_m^T\cdots L_1^T=(L_1\cdots L_m)(L_1\cdots L_m)^T$$

From the block representation, we can see that once we further decompose $K-ww^T/a_{11}$, only the $I$ part in $\begin{bmatrix} \sqrt{a_{11}} & 0\\ w/\sqrt{a_{11}} &
I \end{bmatrix}$ will further be modified while the first column stays the same

This, of course, requires that $K-ww^T/a_{11}$ is PD

We see that $A_1 = L_1^{-1}AL_1^{-T}$

Since $A$ is PD, for any nonzero vector $x$, we have $x^TAx >0$

Then we can define $y=L^Tx$ and we have $x=L^{-T}y$

Plug into the quadratic form

$$x^TAx = y^TL^{-1}AL^{-T}y >0$$

and we know that $A_1 = L_1^{-1}AL_1^{-T}$ is also PD

#### Example

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

plt.style.use('dark_background')
# color: https://matplotlib.org/stable/gallery/color/named_colors.htm

In [ ]:
def cholesky_factorization(A):
    m = A.shape[0]
    l_mat = A.copy().astype(float)

    for k in range(m):
        if l_mat[k, k] <= 0:
            return print('Input is not positive definite')

        # Follow the first step, iteratively apply to a smaller and smaller K
        l_mat[k+1:, k+1:] -= np.outer(l_mat[k+1:, k], l_mat[k+1:, k]) / l_mat[k, k]
        l_mat[k:, k] /= np.sqrt(l_mat[k, k])

    return np.tril(l_mat)

In [ ]:
np.random.seed(42)

# Make PD
A = np.random.rand(6, 6)
A = A.dot(A.T)

l_mat = cholesky_factorization(A)

# Compare to numpy
l_mat_np = np.linalg.cholesky(A)

# Verify factorization
print(f'A:\n{A}')

print(f'\nL:\n{l_mat}')

print(f'\nL_np:\n{l_mat_np}')

print(f'\nLL^T:\n{l_mat @ l_mat.T}')

A:
[[ 1.9870  1.8637  0.8859  1.0728  1.4710  1.2821]
 [ 1.8637  2.5575  0.9867  1.1053  1.2480  1.6979]
 [ 0.8859  0.9867  1.1727  0.8394  0.8816  1.4458]
 [ 1.0728  1.1053  0.8394  0.8848  0.8097  1.0625]
 [ 1.4710  1.2480  0.8816  0.8097  1.4819  1.5215]
 [ 1.2821  1.6979  1.4458  1.0625  1.5215  2.8888]]

L:
[[ 1.4096  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 1.3221  0.8997  0.0000  0.0000  0.0000  0.0000]
 [ 0.6285  0.1731  0.8647  0.0000  0.0000  0.0000]
 [ 0.7610  0.1101  0.3955  0.3702  0.0000  0.0000]
 [ 1.0435 -0.1463  0.2904 -0.2249  0.4864  0.0000]
 [ 0.9095  0.5506  0.9007 -0.1258  0.7464  0.6116]]

L_np:
[[ 1.4096  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 1.3221  0.8997  0.0000  0.0000  0.0000  0.0000]
 [ 0.6285  0.1731  0.8647  0.0000  0.0000  0.0000]
 [ 0.7610  0.1101  0.3955  0.3702  0.0000  0.0000]
 [ 1.0435 -0.1463  0.2904 -0.2249  0.4864  0.0000]
 [ 0.9095  0.5506  0.9007 -0.1258  0.7464  0.6116]]

LL^T:
[[ 1.9870  1.8637  0.8859  1.0728  1.4710  1.2821]
 [ 1.86

In [ ]:
np.random.seed(42)

mat_temp = np.random.rand(6, 5)

# Make PSD
A_psd = mat_temp @ mat_temp.T

l_mat = cholesky_factorization(A_psd)

Input is not positive definite
