#### Factorization of positive definite matrices

Every positive definite matrix $A$ has a Cholesky factorization that is unique

$$A=LL^T$$

where $L$ is lower triangular

To get a feeling of how to find the factorization, we look at the first step (since $A$ is positive definite, $a_{11}>0$)

$$\begin{align*}A &= \begin{bmatrix} a_{11} & w^T \\ w &
K \end{bmatrix} \\
&=\begin{bmatrix} \sqrt{a_{11}} & 0\\ w/\sqrt{a_{11}} &
I \end{bmatrix}\begin{bmatrix} 1 & 0 \\ 0 &
K-ww^T/a_{11}\end{bmatrix}\begin{bmatrix} \sqrt{a_{11}} & w^T/\sqrt{a_{11}} \\ 0 &
I \end{bmatrix} \\
&=L_1A_1L_1^T
\end{align*}$$

We can keep going and decompose $A_1=L_2A_2L_2^T$ and so on and we have

$$A=L_1\cdots L_mL_m^T\cdots L_1^T=(L_1\cdots L_m)(L_1\cdots L_m)^T$$

From the block representation, we can see that once we further decompose $K-ww^T/a_{11}$, only the $I$ part in $\begin{bmatrix} \sqrt{a_{11}} & 0\\ w/\sqrt{a_{11}} &
I \end{bmatrix}$ will further be modified while the first column stays the same

This, of course, requires that $K-ww^T/a_{11}$ is PD

We see that $A_1 = L_1^{-1}AL_1^{-T}$

Since $A$ is PD, for any nonzero vector $x$, we have $x^TAx >0$

Then we can define $y=L^Tx$ and we have $x=L^{-T}y$

Plug into the quadratic form

$$x^TAx = y^TL^{-1}AL^{-T}y >0$$

and we know that $A_1 = L_1^{-1}AL_1^{-T}$ is also PD

#### Example

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

plt.style.use('dark_background')
# color: https://matplotlib.org/stable/gallery/color/named_colors.htm

In [ ]:
def cholesky_factorization(A):
    m = A.shape[0]
    l_mat = A.copy().astype(float)

    for k in range(m):
        if l_mat[k, k] <= 0:
            raise ValueError('Matrix is not positive definite')

        # Follow the first step, iteratively apply to a smaller and smaller K
        l_mat[k+1:, k+1:] -= np.outer(l_mat[k+1:, k], l_mat[k+1:, k]) / l_mat[k, k]
        l_mat[k:, k] /= np.sqrt(l_mat[k, k])

    return np.tril(l_mat)

In [ ]:
np.random.seed(42)

# Make PD
A = np.random.rand(7, 7)
A = A.dot(A.T)

try:
    l_mat = cholesky_factorization(A)

    # Compare to numpy
    l_mat_np = np.linalg.cholesky(A)

    # Verify factorization
    print(f'A:\n{A}')
    print(f'\nL:\n{l_mat}')
    print(f'\nL_np:\n{l_mat_np}')
    print(f'\nLL^T:\n{l_mat @ l_mat.T}')
except Exception as e:
    print(e)

A:
[[ 1.9904  1.7200  0.9277  1.0547  1.0271  1.1900  1.6249]
 [ 1.7200  3.2922  1.2853  1.6022  2.0328  1.6002  1.6246]
 [ 0.9277  1.2853  1.0804  1.1417  1.2858  1.1203  1.2200]
 [ 1.0547  1.6022  1.1417  1.3678  1.1337  1.1742  1.2971]
 [ 1.0271  2.0328  1.2858  1.1337  2.5884  1.2917  1.3745]
 [ 1.1900  1.6002  1.1203  1.1742  1.2917  1.6778  1.2548]
 [ 1.6249  1.6246  1.2200  1.2971  1.3745  1.2548  2.0005]]

L:
[[ 1.4108  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 1.2192  1.3438  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 0.6575  0.3599  0.7201  0.0000  0.0000  0.0000  0.0000]
 [ 0.7476  0.5140  0.6459  0.3571  0.0000  0.0000  0.0000]
 [ 0.7280  0.8522  0.6950 -0.8333  0.3934  0.0000  0.0000]
 [ 0.8435  0.4256  0.5729 -0.1264 -0.4792  0.4599  0.0000]
 [ 1.1518  0.1640  0.5606 -0.0289 -0.0443 -0.2881  0.4969]]

L_np:
[[ 1.4108  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 1.2192  1.3438  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 0.6575  0.3599  0.7201  0.0000  0.000

In [ ]:
np.random.seed(42)

mat_temp = np.random.rand(6, 5)

# Make PSD
A_psd = mat_temp @ mat_temp.T

try:
    l_mat = cholesky_factorization(A_psd)
except Exception as e:
    print(e)

Matrix is not positive definite


#### LDLT factorization for nonsingular symmetric matrices

We can show in case of `nonsingular symmetric` matrix, $A$ can be factorized into lower triangular matrix $L$ and diagonal matrix $D$ such that $A=LDL^T$

Similarly, we start with $A$ as

$$\begin{align*}A &= \begin{bmatrix} a_{11} & w^T \\ w &
K \end{bmatrix} \\
&=\begin{bmatrix} 1 & 0\\ w/a_{11} &
I \end{bmatrix}\begin{bmatrix} a_{11} & 0 \\ 0 &
K-ww^T/a_{11}\end{bmatrix}\begin{bmatrix} 1 & w^T/a_{11} \\ 0 &
I \end{bmatrix} \\
&=L_1D_1L_1^T
\end{align*}$$

We can work just like in Cholesky to decompose the smaller and smaller matrix $K$ and update the submatrix in $L$

For LDLT factoriztaion, the diagonal elements of $L$ are required to be 1 at the cost of introducing an additional diagonal matrix $D$ in the decomposition

In [ ]:
def ldlt_factorization(A):
    # Assume A is symmetric and invertible
    m = A.shape[0]
    l_mat = A.copy().astype(float)
    d_mat = np.zeros(m)

    for k in range(m):
        d_mat[k] = l_mat[k, k]
        if l_mat[k, k] == 0:
            raise ValueError('Matrix is singular')

        l_mat[k+1:, k+1:] -= np.outer(l_mat[k+1:, k], l_mat[k+1:, k]) / l_mat[k, k]
        l_mat[k:, k] /= l_mat[k, k]

    return np.tril(l_mat), np.diag(d_mat)

In [ ]:
np.random.seed(42)

A = np.random.rand(7, 7)
A = (A + A.T) / 2 # Turn to symmetric matrix
A[3:,3:]=0

try:
    L, D = ldlt_factorization(A)
    print("L:\n", L)
    print("D:\n", D)
    print("LDL^T:\n", L @ D @ L.T)
    print("A:\n", A)
    print("Difference:\n", np.linalg.norm(L @ D @ L.T - A))
except ValueError as e:
    print(e)

L:
 [[ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 2.4255  1.0000  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 1.2199  0.4135  1.0000  0.0000  0.0000  0.0000  0.0000]
 [ 0.9854  0.4611  14.4868  1.0000  0.0000  0.0000  0.0000]
 [ 0.9991  0.2493  11.0002  0.7975  1.0000  0.0000  0.0000]
 [ 1.2874  0.3751 -6.9973 -0.4353  277.1035  1.0000  0.0000]
 [ 0.1234 -0.2800  9.3145  0.6972 -163.5905 -0.5982  1.0000]]
D:
 [[ 0.3745  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 0.0000 -1.6023  0.0000  0.0000  0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0208  0.0000  0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000 -4.3805  0.0000  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000  0.0000 -0.0009  0.0000  0.0000]
 [ 0.0000  0.0000  0.0000  0.0000  0.0000  69.8831  0.0000]
 [ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000]]
LDL^T:
 [[ 0.3745  0.9084  0.4569  0.3691  0.3742  0.4822  0.0462]
 [ 0.9084  0.6011  0.4457  0.1564  0.5082  0.5685  0.5608]
 [ 0.4569  0.4457  0.3042  0.44