#### Power iterations for symmetric matrices

So far we know that for `diagonalizable` $A\in \mathbf{R}^{n \times n}$, the method of power iterations finds the dominant eigenvalue and corresponding eigenvector through the following

* starting from $x^0$
* compute $y^k=Ax^{k-1}$
* get new $x^{k}$ by normalizing $y^k$ ($l_2$ norm, infinity norm, etc)
$$x^{k}=\frac{y^k}{\|y^k\|}$$

For which $x^k\rightarrow v_1$, and Rayleigh quotient $\frac{(x^k)^TAx^k}{(x^k)^Tx^k}\rightarrow \lambda_1$

For `symmetric` matrices, we can also update using

$$A\leftarrow A - \lambda_1 v_1 v_1^T$$

and progressively find remaining eigenvalues and eigenvectors, due to the fact that symmetric matrices have orthonormal eigenvectors

#### General eigenvalues problems for nonsymmetric matrices

If matrix $A$ is `nonsymmetric`, we know that we can choose right eigenvector $v$ and left eigenvector $u$ such that

$$u_i^Tv_j = \left\{\begin{array}{rcl}0 &i\neq j \\1 &i=j \end{array}\right.$$

Update to matrix $A$ after getting $\lambda_1, v_1$ can be expressed as

$$A\leftarrow A - \lambda_1 v_1 u_1^T$$

Similarly, what we want is that the updated $A$ still has all remaining $\lambda_i, v_i, i>1$ while making $v_1$ corresponding to a zero eigenvalue, and we can again verify both

$$\begin{align*}
&(A - \lambda_1 v_1 u_1^T)v_1 \\
&=Av_1-\lambda_1v_1(u_1^Tv_1)\\
& u_1^Tv_1=1 \\
&=Av_1-\lambda_1v_1\\
&=0
\end{align*}$$

and

$$\begin{align*}
&(A - \lambda_1 v_1 u_1^T)v_i \\
&=Av_i-\lambda_1v_1(u_1^Tv_i)\\
& u_i^Tv_1=0,\forall i\neq 1 \\
&=Av_i\\
&=\lambda_iv_i
\end{align*}$$

We see that such update of $A$ allows to preserve all remaining eigenvalues/eigenvectors of $A$, while adding a zero eigenvalue, which allows power iterations to correctly converge to remaining eigenvalues and eigenvectors

In [55]:
import matplotlib.pyplot as plt
import numpy as np
np.set_printoptions(formatter={'float': '{: 0.4f}'.format})

plt.style.use('dark_background')
# color: https://matplotlib.org/stable/gallery/color/named_colors.htm

In [56]:
def power_iteration_nonsymmetric(A, num_eigen, num_iter=5000, converge_tol=1e-10, eigen_tol=1e-10):
    n = A.shape[0]
    eigenvalues = []
    right_eigenvectors = []
    left_eigenvectors = []
    A_current = A.copy()

    for k in range(num_eigen):
        v = np.random.rand(n)
        v /= np.linalg.norm(v)
        u = np.random.rand(n)
        u /= np.linalg.norm(u)

        for j in range(num_iter):
            # Right eigenvector
            y = A_current @ v
            norm_y = np.linalg.norm(y)
            if norm_y < eigen_tol:
                print(f"Norm of (#{k+1}) right eigenvector is too small, stopping iteration")
                break
            v_next = y / norm_y

            # Left eigenvector
            z = A_current.T @ u
            norm_z = np.linalg.norm(z)
            if norm_z < eigen_tol:
                print(f"Norm of (#{k+1}) left eigenvector is too small, stopping iteration")
                break
            u_next = z / norm_z

            # Check convergence
            if np.linalg.norm(v_next - v) < converge_tol and np.linalg.norm(u_next - u) < converge_tol:
                break

            v = v_next
            u = u_next

        if norm_y < eigen_tol or norm_z < eigen_tol:
            continue

        print(f'{j+1} iterations for eigenvalue #{k+1}')

        # Normalize u and v such that u^Tv = 1
        scaling = u @ v
        if abs(scaling) < eigen_tol:
            print(f"Scaling factor u^Tv is too small, cannot normalize")
            continue
        v = v / scaling

        # Rayleigh quotient using right eigenvectors
        eigenvalue = v @ (A_current @ v) / (v @ v)

        if abs(eigenvalue) < eigen_tol:
            print(f"Eigenvalue {eigenvalue} is too small and is ignored")
            continue

        eigenvalues.append(eigenvalue)
        right_eigenvectors.append(v)
        left_eigenvectors.append(u)

        A_current = A_current - eigenvalue * np.outer(v, u)

    if not eigenvalues:
        print("No valid eigenvalues found.")
        return np.array([]), np.array([]), np.array([])

    return np.array(eigenvalues), np.column_stack(right_eigenvectors), np.column_stack(left_eigenvectors)

In [57]:
np.random.seed(1)

A = np.random.rand(4, 4)

# A = np.array([[8, 3],[2, 7]])
k = A.shape[0]

eigenvalues, right_eigenvectors, left_eigenvectors = power_iteration_nonsymmetric(A, k)

# Normalize right eigenvectors and adjust left eigenvectors
for i in range(right_eigenvectors.shape[1]):
    v = right_eigenvectors[:, i]
    u = left_eigenvectors[:, i]
    norm_v = np.linalg.norm(v)
    if norm_v < 1e-6:
        print(f"Norm of right eigenvector #{i+1} is too small, cannot normalize")
        continue
    # To be consistent with NumPy
    v_normalized = v / norm_v
    # To ensure biorthogonality
    u_adjusted = u * norm_v

    right_eigenvectors[:, i] = v_normalized
    left_eigenvectors[:, i] = u_adjusted

    print(f"u_{i+1}^T v_{i+1} = {v_normalized @ u_adjusted:.4f}")

print("\nComputed eigenvalues")
for idx, eigenvalue in enumerate(eigenvalues, 1):
    print(f"# {idx}: {eigenvalue:.4f}")

print("\nComputed right eigenvectors (columns)")
print(right_eigenvectors)

print("\nComputed left eigenvectors (columns)")
print(left_eigenvectors)

# Compare with NumPy's outcomes
eigenvalues_np, right_eigenvectors_np = np.linalg.eig(A)
print("\nEigenvalues from NumPy")
print(eigenvalues_np)

print("\nRight eigenvectors from NumPy")
print(right_eigenvectors_np)

# Reconstruct A using left/right eigenvectors
A_reconstructed = right_eigenvectors @ np.diag(eigenvalues) @ left_eigenvectors.T

print("\nA reconstructed")
print(A_reconstructed)

print("\nOriginal A")
print(A)

# Check error
reconstruction_error = np.linalg.norm(A - A_reconstructed)
print(f"\nReconstruction error: {reconstruction_error}")

15 iterations for eigenvalue #1
127 iterations for eigenvalue #2
5000 iterations for eigenvalue #3
2 iterations for eigenvalue #4
u_1^T v_1 = 1.0000
u_2^T v_2 = 1.0000
u_3^T v_3 = 1.0000
u_4^T v_4 = 1.0000

Computed eigenvalues
# 1: 1.3567
# 2: 0.2564
# 3: -0.2090
# 4: 0.1949

Computed right eigenvectors (columns)
[[ 0.3880  0.4321  0.4665 -0.1869]
 [ 0.2900  0.1211 -0.6269  0.2021]
 [ 0.7073  0.7279 -0.3327  0.8976]
 [ 0.5149 -0.5184  0.5279 -0.3444]]

Computed left eigenvectors (columns)
[[ 0.4109  1.3407 -0.0065 -1.4135]
 [ 0.9057  0.2704 -1.6180 -1.5327]
 [ 0.2046 -0.1492  0.4678  1.2474]
 [ 0.8414 -0.9577  0.2735  0.2151]]

Eigenvalues from NumPy
[ 1.3567  0.2564  0.1949 -0.2090]

Right eigenvectors from NumPy
[[-0.3880 -0.4321  0.1869  0.4665]
 [-0.2900 -0.1211 -0.2021 -0.6269]
 [-0.7073 -0.7279 -0.8976 -0.3327]
 [-0.5149  0.5184  0.3444  0.5279]]

A reconstructed
[[ 0.4170  0.7203  0.0001  0.3023]
 [ 0.1468  0.0923  0.1863  0.3456]
 [ 0.3968  0.5388  0.4192  0.6852]
 [ 0.2045  0